# Generated by Django 5.1.4 on 2024-12-27 19:07

import django.db.models.deletion
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', mdeditor.fields.MDTextField()),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search_app.participant')),
            ],
        ),
    ]
