# Generated by Django 5.1.4 on 2024-12-27 19:23

import django.db.models.deletion
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectableShoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year_produced', models.PositiveIntegerField()),
                ('collaboration_artist', models.CharField(blank=True, max_length=100, null=True)),
                ('sku_code', models.CharField(max_length=50, unique=True)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_on_release', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('VR', 'Very Rare'), ('UR', 'Ultra Rare')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', mdeditor.fields.MDTextField()),
                ('shoe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search_app.collectableshoe')),
            ],
        ),
    ]
