# Generated by Django 5.1.4 on 2024-12-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_collectableshoe_shoedescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bio',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
